# Generated by Django 6.0.1 on 2026-01-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
